// import { createElement } from 'lwc';
import ParentComp_LIFECYCLE_LWC from 'c/parentComp_LIFECYCLE_LWC';

describe('c-parent-comp-l-i-f-e-c-y-c-l-e-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-parent-comp-l-i-f-e-c-y-c-l-e-lwc', {
            is: ParentComp_LIFECYCLE_LWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});